
#########################################
#              API - ROUTES             #
#########################################

@PORT = 4000
@TO  = "+2347010642657"


### Check if API is working 
GET http://localhost:{{PORT}} HTTP/1.1

### Check Client status if its logged in or not
GET http://localhost:{{PORT}}/auth/checkauth HTTP/1.1
accept: * 
content-type: application/json

### Check Client status if its logged in or not
GET http://localhost:{{PORT}}/auth/getqr HTTP/1.1
accept: * 
content-type: application/json

### search client messages with request query as query while the limit and page is optional
GET http://localhost:{{PORT}}/api/messages?query="howfa" HTTP/1.1
accept: * 
content-type: application/json

### check common groups between a client and contact (response not what is expected)
GET http://localhost:{{PORT}}/api/groups/+2348105463507 HTTP/1.1
accept: * 
content-type: application/json

###Send Message to a contact
POST http://localhost:{{PORT}}/api/whatsapp/send/message HTTP/1.1
accept: * 
content-type: application/json

{
    "phone"    : {{TO}},
    "message"  : "BOT TESTING. Do not take too serious"
}
###Send location to a contact
POST http://localhost:{{PORT}}/api/send/location HTTP/1.1
accept: * 
content-type: application/json

{
    "phone"    : {{TO}},
    "latitude": 67,
    "longtitude":80,
    "description":"this is it"
}
###Send Image to a contact
POST http://localhost:{{PORT}}/api/send/image HTTP/1.1
accept: * 
content-type: application/json

{
    "phone"    : {{TO}},
    "mediaUrl": "https://via.placeholder.com/350x150.png",
    "caption":"this is it"
}

###Change Clients profile status
POST http://localhost:{{PORT}}/api/set/status HTTP/1.1
accept: * 
content-type: application/json

{
    "status"    : "On it!!" 
}

###Change clients display name 
POST http://localhost:{{PORT}}/api/change/displayname HTTP/1.1
accept: * 
content-type: application/json

{
    "displayName"    : "GH`ded" 
}
###Create group(not working)
POST http://localhost:{{PORT}}/api/create/group HTTP/1.1
accept: * 
content-type: application/json

{
    "title"    : "my bot group", 
    "participants":[{{TO}}] 
}
### Client Logout
GET http://localhost:{{PORT}}/api/logout HTTP/1.1
accept: * 
content-type: application/json

